# [dbo].[ExamenAdmision]

In [0]:
USE [kalum_test1]
GO

In [0]:
/****** Object:  Table [dbo].[ExamenAdmision]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExamenAdmision](
	[ExamenId] [varchar](128) NOT NULL,
	[FechaExamen] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ExamenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Aspirante]

In [0]:
/****** Object:  Table [dbo].[Aspirante]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aspirante](
	[NoExpediente] [varchar](128) NOT NULL,
	[Apellidos] [varchar](128) NOT NULL,
	[Nombres] [varchar](128) NOT NULL,
	[Direccion] [varchar](128) NOT NULL,
	[Telefono] [varchar](64) NOT NULL,
	[Email] [varchar](128) NOT NULL,
	[Estatus] [varchar](32) NULL,
	[CarreraId] [varchar](128) NOT NULL,
	[ExamenId] [varchar](128) NOT NULL,
	[JornadaId] [varchar](128) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NoExpediente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[vw_ListarAspirantesPorFechaExamen]

In [0]:
/****** Object:  View [dbo].[vw_ListarAspirantesPorFechaExamen]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[vw_ListarAspirantesPorFechaExamen]
as
select a.NoExpediente, a.Apellidos, a.Nombres, a.Estatus, ea.FechaExamen
	from Aspirante a inner join ExamenAdmision ea on a.ExamenId = ea.ExamenId;
GO

# [dbo].[Alumno]

In [0]:
/****** Object:  Table [dbo].[Alumno]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alumno](
	[Carne] [varchar](8) NOT NULL,
	[Apellidos] [varchar](128) NOT NULL,
	[Nombres] [varchar](128) NOT NULL,
	[Direccion] [varchar](128) NOT NULL,
	[Telefono] [varchar](64) NOT NULL,
	[Email] [varchar](64) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Carne] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Cargo]

In [0]:
/****** Object:  Table [dbo].[Cargo]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cargo](
	[CargoId] [varchar](128) NOT NULL,
	[Descripcion] [varchar](128) NOT NULL,
	[Prefijo] [varchar](64) NOT NULL,
	[Monto] [decimal](10, 2) NOT NULL,
	[GeneraMora] [bit] NOT NULL,
	[PorcentajeMora] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CargoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CarreraTecnica]

In [0]:
/****** Object:  Table [dbo].[CarreraTecnica]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarreraTecnica](
	[CarreraId] [varchar](128) NOT NULL,
	[Nombre] [varchar](128) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CarreraId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CuentaXCobrar]

In [0]:
/****** Object:  Table [dbo].[CuentaXCobrar]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CuentaXCobrar](
	[Cargo] [varchar](128) NOT NULL,
	[Anio] [varchar](4) NOT NULL,
	[Carne] [varchar](8) NOT NULL,
	[CargoId] [varchar](128) NOT NULL,
	[Descripcion] [varchar](128) NOT NULL,
	[FechaCargo] [datetime] NOT NULL,
	[FechaAplica] [datetime] NOT NULL,
	[Monto] [decimal](10, 2) NOT NULL,
	[Mora] [decimal](10, 2) NOT NULL,
	[Descuento] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Cargo] ASC,
	[Anio] ASC,
	[Carne] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Inscripcion]

In [0]:
/****** Object:  Table [dbo].[Inscripcion]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inscripcion](
	[InscripcionId] [varchar](128) NOT NULL,
	[Carne] [varchar](8) NOT NULL,
	[CarreraId] [varchar](128) NOT NULL,
	[JornadaId] [varchar](128) NOT NULL,
	[Ciclo] [varchar](4) NOT NULL,
	[FechaInscripcion] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[InscripcionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[InscripcionPago]

In [0]:
/****** Object:  Table [dbo].[InscripcionPago]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InscripcionPago](
	[BoletaPago] [varchar](128) NOT NULL,
	[NoExpediente] [varchar](128) NOT NULL,
	[Anio] [varchar](4) NOT NULL,
	[FechaPago] [datetime] NOT NULL,
	[Monto] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BoletaPago] ASC,
	[NoExpediente] ASC,
	[Anio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[InversionCarreraTecnica]

In [0]:
/****** Object:  Table [dbo].[InversionCarreraTecnica]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InversionCarreraTecnica](
	[InversionId] [varchar](128) NOT NULL,
	[CarreraId] [varchar](128) NOT NULL,
	[MontoInscripcion] [decimal](10, 2) NOT NULL,
	[NumeroPagos] [int] NOT NULL,
	[MontoPago] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[InversionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Jornada]

In [0]:
/****** Object:  Table [dbo].[Jornada]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jornada](
	[JornadaId] [varchar](128) NOT NULL,
	[Prefijo] [varchar](2) NOT NULL,
	[Descripcion] [varchar](128) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[JornadaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ResultadoExamenAdmsion]

In [0]:
/****** Object:  Table [dbo].[ResultadoExamenAdmsion]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ResultadoExamenAdmsion](
	[NoExpediente] [varchar](128) NOT NULL,
	[Anio] [varchar](4) NOT NULL,
	[Descripcion] [varchar](128) NOT NULL,
	[nota] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[NoExpediente] ASC,
	[Anio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF__Aspirante__Estat__2B3F6F97]

In [0]:
ALTER TABLE [dbo].[Aspirante] ADD  DEFAULT ('No Asignado') FOR [Estatus]
GO

# [DF__ResultadoE__nota__30F848ED]

In [0]:
ALTER TABLE [dbo].[ResultadoExamenAdmsion] ADD  DEFAULT ((0)) FOR [nota]
GO

# [FK_ASPIRANTE_CARRERA_TECNICA]

In [0]:
ALTER TABLE [dbo].[Aspirante]  WITH CHECK ADD  CONSTRAINT [FK_ASPIRANTE_CARRERA_TECNICA] FOREIGN KEY([CarreraId])
REFERENCES [dbo].[CarreraTecnica] ([CarreraId])
GO
ALTER TABLE [dbo].[Aspirante] CHECK CONSTRAINT [FK_ASPIRANTE_CARRERA_TECNICA]
GO

# [FK_ASPIRANTE_EXAMEN_ADMISION]

In [0]:
ALTER TABLE [dbo].[Aspirante]  WITH CHECK ADD  CONSTRAINT [FK_ASPIRANTE_EXAMEN_ADMISION] FOREIGN KEY([ExamenId])
REFERENCES [dbo].[ExamenAdmision] ([ExamenId])
GO
ALTER TABLE [dbo].[Aspirante] CHECK CONSTRAINT [FK_ASPIRANTE_EXAMEN_ADMISION]
GO

# [FK_ASPIRANTE_JORNADA]

In [0]:
ALTER TABLE [dbo].[Aspirante]  WITH CHECK ADD  CONSTRAINT [FK_ASPIRANTE_JORNADA] FOREIGN KEY([JornadaId])
REFERENCES [dbo].[Jornada] ([JornadaId])
GO
ALTER TABLE [dbo].[Aspirante] CHECK CONSTRAINT [FK_ASPIRANTE_JORNADA]
GO

# [FK_CUENTA_X_COBRAR_ALUMNO]

In [0]:
ALTER TABLE [dbo].[CuentaXCobrar]  WITH CHECK ADD  CONSTRAINT [FK_CUENTA_X_COBRAR_ALUMNO] FOREIGN KEY([Carne])
REFERENCES [dbo].[Alumno] ([Carne])
GO
ALTER TABLE [dbo].[CuentaXCobrar] CHECK CONSTRAINT [FK_CUENTA_X_COBRAR_ALUMNO]
GO

# [FK_CUENTA_X_COBRAR_CARGO]

In [0]:
ALTER TABLE [dbo].[CuentaXCobrar]  WITH CHECK ADD  CONSTRAINT [FK_CUENTA_X_COBRAR_CARGO] FOREIGN KEY([CargoId])
REFERENCES [dbo].[Cargo] ([CargoId])
GO
ALTER TABLE [dbo].[CuentaXCobrar] CHECK CONSTRAINT [FK_CUENTA_X_COBRAR_CARGO]
GO

# [FK_INSCRIPCION_ALUMNO]

In [0]:
ALTER TABLE [dbo].[Inscripcion]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_ALUMNO] FOREIGN KEY([Carne])
REFERENCES [dbo].[Alumno] ([Carne])
GO
ALTER TABLE [dbo].[Inscripcion] CHECK CONSTRAINT [FK_INSCRIPCION_ALUMNO]
GO

# [FK_INSCRIPCION_CARRERA_TECNICA]

In [0]:
ALTER TABLE [dbo].[Inscripcion]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_CARRERA_TECNICA] FOREIGN KEY([CarreraId])
REFERENCES [dbo].[CarreraTecnica] ([CarreraId])
GO
ALTER TABLE [dbo].[Inscripcion] CHECK CONSTRAINT [FK_INSCRIPCION_CARRERA_TECNICA]
GO

# [FK_INSCRIPCION_JORNADA]

In [0]:
ALTER TABLE [dbo].[Inscripcion]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_JORNADA] FOREIGN KEY([JornadaId])
REFERENCES [dbo].[Jornada] ([JornadaId])
GO
ALTER TABLE [dbo].[Inscripcion] CHECK CONSTRAINT [FK_INSCRIPCION_JORNADA]
GO

# [FK_INSCRIPCION_PAGO_ASPIRANTE]

In [0]:
ALTER TABLE [dbo].[InscripcionPago]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_PAGO_ASPIRANTE] FOREIGN KEY([NoExpediente])
REFERENCES [dbo].[Aspirante] ([NoExpediente])
GO
ALTER TABLE [dbo].[InscripcionPago] CHECK CONSTRAINT [FK_INSCRIPCION_PAGO_ASPIRANTE]
GO

# [FK_INVERSION_CARRERA_TECNICA]

In [0]:
ALTER TABLE [dbo].[InversionCarreraTecnica]  WITH CHECK ADD  CONSTRAINT [FK_INVERSION_CARRERA_TECNICA] FOREIGN KEY([CarreraId])
REFERENCES [dbo].[CarreraTecnica] ([CarreraId])
GO
ALTER TABLE [dbo].[InversionCarreraTecnica] CHECK CONSTRAINT [FK_INVERSION_CARRERA_TECNICA]
GO

# [FK_RESULTADO_EXAMEN_ADMISION_ASPIRANTE]

In [0]:
ALTER TABLE [dbo].[ResultadoExamenAdmsion]  WITH CHECK ADD  CONSTRAINT [FK_RESULTADO_EXAMEN_ADMISION_ASPIRANTE] FOREIGN KEY([NoExpediente])
REFERENCES [dbo].[Aspirante] ([NoExpediente])
GO
ALTER TABLE [dbo].[ResultadoExamenAdmsion] CHECK CONSTRAINT [FK_RESULTADO_EXAMEN_ADMISION_ASPIRANTE]
GO

# [dbo].[sp_EnrollmentProcess]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_EnrollmentProcess]    Script Date: 09-Jul-22 11:38:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[sp_EnrollmentProcess] @NoExpediente varchar(12), @Ciclo varchar(4), @MesInicioPago int, @CarreraId varchar(128)
as
begin
	-- Variables para informacion de aspirantes
	declare @Apellidos varchar(128)
	declare @Nombres varchar(128)
	declare @Direccion varchar(128)
	declare @Telefono varchar(64)
	declare @Email varchar(64)
	declare @JornadaId varchar(128)
	-- Variables para generar numero de carne
	declare @Exists int
	declare @Carne varchar(12)
	-- Variables para proceso de pago
	declare @MontoInscripcion numeric(10,2)
	declare @NumeroPagos int
	declare @MontoPago numeric(10,2)
	declare @Descripcion varchar(128)
	declare @Prefijo varchar(6)
	declare @CargoId varchar(128)
	declare @Monto numeric(10,2)
	declare @CorrelativoPagos int
	-- Inicio transaccion
	begin transaction
	begin try
		-- Informacion del aspirante
		select @Apellidos = apellidos, 
		@Nombres = Nombres, 
		@Direccion = Direccion, 
		@Telefono = Telefono, 
		@Email = Email, 
		@JornadaId = JornadaId 
		from Aspirante where NoExpediente = @NoExpediente
		-- Generar Carne
		set @Exists = (select top 1 a.Carne from Alumno a where SUBSTRING(a.Carne, 1,4) = @Ciclo order by a.Carne desc)
		if @Exists is NULL
		begin
			set @Carne = (@Ciclo * 10000) + 1
		end
		else
		begin
			set @Carne = (select top 1 a.Carne from Alumno a where SUBSTRING(a.Carne, 1,4) = @Ciclo order by a.Carne desc) + 1
		end
		-- Registrar Alumno
		insert into Alumno VALUES (@Carne, @Apellidos, @Nombres, @Direccion, @Telefono, concat(@Carne,@Email))
		-- Registrar Inscripcion
		insert into Inscripcion VALUES (NEWID(), @Carne, @CarreraId, @JornadaId, @Ciclo,getDate())
		-- Actualizar estado de aspirante
		update Aspirante set Estatus = 'INSCRITO CICLO ' + @Ciclo where NoExpediente = @NoExpediente

	-- Proceso de cargos
		select @MontoInscripcion = MontoInscripcion, @NumeroPagos = NumeroPagos, @MontoPago = MontoPago 
			from InversionCarreraTecnica where CarreraId = @CarreraId
		select @CargoId = CargoId, @Descripcion = Descripcion, @Prefijo = Prefijo 
			from Cargo where CargoId = 'C2B9C413-1D70-4113-AD11-EFC94FE7B9AE' /* Codigo pago de inscripcion tabla Cargo */
		-- Insertar cargos
		insert into CuentaXCobrar VALUES(CONCAT(@Prefijo, SUBSTRING(@Ciclo, 3,2), dbo.LPAD('1', 2, '0')), @Ciclo, @Carne, @cargoId, @Descripcion, getdate(), getdate(), @MontoInscripcion, 0,0)
		-- Insertar Cargo Carne
		select @CargoId = CargoId, @Descripcion = Descripcion, @Prefijo = Prefijo, @Monto = Monto 
			from Cargo where CargoId = 'FADCEEF1-9B2F-4778-B92D-24A515583743' /* Codigo cargo carne de tabla cargo */
		insert into CuentaXCobrar VALUES(CONCAT(@Prefijo, SUBSTRING(@Ciclo, 3,2), dbo.LPAD('1', 2, '0')), @Ciclo, @Carne, @cargoId, @Descripcion, getdate(), getdate(), @Monto, 0,0)

		-- Cargos Mensuales
		set @CorrelativoPagos = 1
		select @CargoId = CargoId, @Descripcion = Descripcion, @Prefijo = Prefijo from Cargo where CargoId = 'A194ACA5-EE44-493B-845F-F5EE032957BC' /* Codigo cargo pago mensual de carrera de tabla cargo */
		while(@CorrelativoPagos <= @NumeroPagos)
		begin
		insert into CuentaXCobrar VALUES(CONCAT(@Prefijo, SUBSTRING(@Ciclo, 3,2), dbo.LPAD(@CorrelativoPagos, 2, '0')), @Ciclo, @Carne, @cargoId, @Descripcion, getdate(), CONCAT(@ciclo,'-',dbo.LPAD(@MesInicioPago,2,'0'),'-','05'), @MontoPago, 0,0)
		set @CorrelativoPagos += 1
		set @MesInicioPago += 1
		end

		commit transaction
		select 'TRANSACTION SUCCESS' AS status, @Carne as carne
	end try
	begin catch
		/*SELECT
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_STATE() AS ErrorState
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage*/
		rollback transaction
		select 'TRANSACTION ERROR' AS status, 0 as carne
	end catch
end
GO